import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Jersey_10 } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { UserContextProvider } from "@/context/UserDetailContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pixelifySans = Jersey_10({
  variable: "--font-pixelify-sans",
  subsets: ["latin"],
  weight: ["400"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that provides global app wrappers, HTML structure, and font variables.
 *
 * Renders an HTML document shell with language and hydration attributes, applies global font CSS variables
 * and antialiasing to the body, and wraps `children` with authentication, user context, and theme providers.
 *
 * @param children - The page or application content to be rendered inside the layout
 * @returns The root HTML structure containing global providers and the rendered `children`
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${pixelifySans.variable} ${inter.variable} antialiased`}
        >
          <UserContextProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </UserContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}